### PR TITLE
Add Eclipse target to build.xml

### PR DESCRIPTION
**Pull request by lewismc**
This PR proposes to build an Eclipse project for Joshua meaning that development from within Eclipse is a piece of cake.

### CODE REVIEW

**Comment by chrismattmann** [comment]
+1

**Comment by mjpost** [comment]
I'll pull this in, but can you explain what it does and how it works?

Related, I use Eclipse, but haven't figured out how to include all of our [coding conventions](http://www.cs.jhu.edu/~post/joshua-docs/documentation.html) in the project itself, and make it easy for people to load them (or tell them how to). If you have any advice on this I'd welcome it.

**Comment by mjpost** [comment]
Also, we're already using Ivy. Is it possible to fetch the ant-eclipse library that way instead of creating the "ant-eclipse-download" ant build target and dependency?

**Comment by lewismc** [comment]
> I'll pull this in, but can you explain what it does and how it works?

OK, so now in order to work with Joshua from within Eclipse you just need to execute 'ant javadoc'. This generates the Eclipse project files and all of the project definitions. You can then do File > Import > Java Project. You will then be able to work with Joshua within Eclipse no problems.

**Comment by lewismc** [comment]
> Related, I use Eclipse, but haven't figured out how to include all of our coding conventions in the project itself, and make it easy for people to load them (or tell them how to). If you have any advice on this I'd welcome it.

Yes, we could just create an eclipse-codeformatter.xml file which can be added to the repository. This can embed and implement the Style guide but this is separate from implementing a project build. I can implement this and submit it as a separate issue.

**Comment by lewismc** [comment]
Can you try using the ant eclipse target and then we can iterate from there?

**Comment by mjpost** [comment]
Okay, I pulled this in [on a new branch](https://github.com/joshua-decoder/joshua/tree/lewismc-eclipse_target). A few notes:

- I had to fix the src target (src/joshua -> src)
- I had to remove the thrax/src and kenlm/src source targets, which caused a lot of problems. Also, thrax is a git submodule, so I'm not sure that it should be in there.

It seems that `.classpath` is now generated from the ant build target. So perhaps this file should be removed from the repo?

**Comment by lewismc** [comment]
ACK
> It seems that .classpath is now generated from the ant build target. So perhaps this file should be removed from the repo?

I agree.

**Comment by mjpost** [comment]
Okay, done.

If you know how to add the code formatter, I'd love to pull that in, as well.

**Comment by mjpost** [comment]
I merged this, but can you fix the following?

- eclipse appears to be using build/ instead of class/, it should be consistent with what Ant uses (use ${build})
- kenlm should not be copied to build/, it's under src but should be ignored by eclipse (it might be fine to move it to the top level directory)

**Comment by lewismc** [comment]
Please see https://github.com/joshua-decoder/joshua/pull/223

**Pull request merged**
