### PR TITLE
ClassLM feature function is written to joshua.config now

### PR DESCRIPTION
**Pull request by noisychannel**
Encountered a slight bug in the pipeline when creating class LMs. This fixes the issue.

### CODE REVIEW

**Comment by mjpost** [comment]
I don't think this line will parse:

**Comment by mjpost** [comment]
Also -- what are you using to build class-based LMs? If you give me an example usage, I will add an option for the pipeline to build it automatically (e.g., a script that takes a corpus on STDIN, write a mapped corpus to STDOUT and the map file to a specified argument).

**Comment by noisychannel** [comment]
`
push(@feature_functions, "LanguageModel -lm_type kenlm -lm_order 9 -lm_file $RUNDIR/class_lm.gz -lm_class -class_map $CLASS_MAP");
`

works. I tried this out with a full pipeline run and the featurefunction was inserted successfully into joshua.config

**Comment by noisychannel** [comment]
This requires two things : 
1. I build the classes using word2vec. This yields a map (word -> class)
2. Using the classes, a class based corpus is created. Here's the script I use : https://gist.github.com/noisychannel/2c710ad641bd0e6ab288

It may be best if you can include this script with Joshua. That way the only thing that needs to be specified is this map (which should ideally be software independent anyway). Then, the LM corpus can be used to build the class LM corpus. 

Thoughts ?

**Comment by mjpost** [comment]
I think the way to do this is:

-  Provide an pipeline argument, --class-mapper, which defaults to some script in `$JOSHUA/scripts/training/class-lm/`

- This script takes a corpus and generates the class'ed version of the corpus and dumps the mapping

-  The script has the following interface:

       cat CORPUS | script.sh -map /path/to/generated/map > CORPUS.CLASS

- There is a default script using Brown clusters or word2vec or Pushpendre's multiview LSA or whatever

- Anyone can provide their own clustering just by specifying `--class-mapper /path/to/script` to the pipeline

Can you point me to your scripts that generate word2vec clusters? (Did you do Brown clustering?) It would be nice to build the building into the pipeline.

**Pull request merged**
