### PR TITLE
Allow reading of gzipped binary berkeleylm.

### PR DESCRIPTION
**Pull request by fhieber**
pull request for #194.
Unfortunately the LM readers do not throw exceptions so I had to catch RuntimeException. Let me know if this is ok here.

### CODE REVIEW

**Comment by mjpost** [comment]
Hi — Did you test this in all scenarios?

- Uncompressed ARPA file
- Compressed ARPA file
- Uncompressed binary file
- Compressed binary file

It would be great to make a small test example under test/berkeley-lm or something. If you are willing to do this, I will provide some instructions.

**Comment by fhieber** [comment]
I did, but did not know where and how to add a unit test for this. I wrote a small main tool though while writing the fix (using a tiny toy lm):
```
public static void main(String[] args) {
        JoshuaConfiguration joshuaConfiguration;
        Decoder decoder;
        Decoder.VERBOSE = 0;
        
        System.err.println("\n=== ARPA ===");
        joshuaConfiguration = new JoshuaConfiguration();
        joshuaConfiguration.features.add("LanguageModel -lm_type berkeleylm -lm_order 3 -lm_file /Users/fhieber/mtproject/playground/joshua/lm.arpa");
        decoder = new Decoder(joshuaConfiguration, "");
        
        System.err.println("\n=== ARPA.GZ ===");
        joshuaConfiguration = new JoshuaConfiguration();
        joshuaConfiguration.features.add("LanguageModel -lm_type berkeleylm -lm_order 3 -lm_file /Users/fhieber/mtproject/playground/joshua/lm.arpa.gz");
        decoder = new Decoder(joshuaConfiguration, "");
        
        System.err.println("\n=== BINARY ===");
        joshuaConfiguration = new JoshuaConfiguration();
        joshuaConfiguration.features.add("LanguageModel -lm_type berkeleylm -lm_order 3 -lm_file /Users/fhieber/mtproject/playground/joshua/lm.binary");
        decoder = new Decoder(joshuaConfiguration, "");
        
        System.err.println("\n=== BINARY.gz ===");
        joshuaConfiguration = new JoshuaConfiguration();
        joshuaConfiguration.features.add("LanguageModel -lm_type berkeleylm -lm_order 3 -lm_file /Users/fhieber/mtproject/playground/joshua/lm.binary.gz");
        decoder = new Decoder(joshuaConfiguration, "");
        
        System.err.println("\n=== NOT EXISTS ===");
        joshuaConfiguration = new JoshuaConfiguration();
        joshuaConfiguration.features.add("LanguageModel -lm_type berkeleylm -lm_order 3 -lm_file /Users/fhieber/mtproject/playground/joshua/NOTEXISTS");
        decoder = new Decoder(joshuaConfiguration, "");
}
```
If you can tell me what kind of tests Joshua supports and how to integrate a new one (JUnit/TestNG?), I am happy to do this.

**Comment by mjpost** [comment]
Can you share the LMs with me? I don't have test documentation, so I'll create this myself and show it to you.

**Comment by mjpost** [comment]
Actually, nevermind, I just made one. Will test soon.

**Comment by mjpost** [comment]
Looks good (and also a lot simpler), thanks!

**Comment by fhieber** [comment]
Cool, thanks for merging! However, you seem to use the same lm file throughout your file loop in the test script  (you should change 'lm.berkeleylm.gz' to '$file').

**Comment by mjpost** [comment]
Right :). Fixed in fe4f81d6edcb2cc2f6f48451150f8d01e50ebdf5

**Pull request merged**
