### PR TITLE
eclipse target to use class/ for build output as well as removal of kenlm from eclipse definition

### PR DESCRIPTION
**Pull request by lewismc**
This PR addresses the final conversation/conversation over on 
https://github.com/joshua-decoder/joshua/pull/220#issuecomment-146187064

### CODE REVIEW

**Comment by mjpost** [comment]
@lewismc, have you tested this? It does not work for me. Putting the line

            <source path="${basedir}/src/joshua" />

does exclude `kenlm/` and under dirs under `src/`, but then eclipse cannot resolve any packages, since it thinks they must be relative to `src/joshua` instead of `src` (e.g., it wants "import decoder" instead of "import joshua.decoder").

It seems that the way to handle this is to keep the source path to `${basedir}/src` but [add an inclusion tag](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Fconcepts%2Fconcept-inclusion-exclusion-patterns.htm) such that only the java files are loaded by eclipse.

**Comment by mjpost** [comment]
FYI, this is what we want to have produced in the .classpath file:

      <classpathentry kind="src" path="src/" including="**/*.java" />

But I don't know how to make ant-eclipse generate this.

Also, I get errors about recursive includes because you are placing the ant-eclipse jar file under $build. I think this should go in lib/ instead.

**Comment by mjpost** [comment]
@lewismc, can you check that the changes I pushed up work for you? I ran into some troubles and think I have resolved them, but it would be good to get confirmation from others.

(Also, I haven't been able to figure out how to get the eclipse target to generate the classpathentry line like above (with the including= attribute), unfortunately; if you have any ideas, that would be great)

**Comment by lewismc** [comment]
Hi @mjpost scoping now sorry for delay

**Pull request merged**
